booknook/library/urls.py
from django.urls import path
from .views import BookListView, AuthorListView, GenreListView, BookDetailView, AuthorDetailView, LoanedBooksByUserListView, BorrowBookView



urlpatterns = [
    path('', BookListView.as_view(), name='books'),
    path('authors/', AuthorListView.as_view(), name='authors'),
    path('genres/', GenreListView.as_view(), name='genres'),
    path('book/<int:pk>', BookDetailView.as_view(), name='book-detail'),
    path('author/<int:pk>', AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', LoanedBooksByUserListView.as_view(), name='borrowed-books'),
    path('book/<int:pk>/borrow/', BorrowBookView.as_view(), name='borrow-book'),
    path('book/<int:pk>/action/', LoanedBooksByUserListView.as_view() , name='book-action')
]

booknook/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.register, name='register'),
    path('accounts/register_sucess/', views.register_success, name='register_success')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booknook/library/models.py
from django.db import models
from django.urls import reverse
from django.db.models import UniqueConstraint 
from django.db.models.functions import Lower
import uuid
from django.conf import settings
from datetime import date, timedelta



class Book(models.Model):
    title = models.CharField(max_length=200)
    publication_date = models.DateField(null=True, blank=True)
    author = models.ForeignKey('Author', on_delete=models.RESTRICT)
    # whether book is part of a series
    series = models.ForeignKey('Series', on_delete=models.SET_NULL, null=True, blank=True)
    # what number the book is in the series sequence
    num_in_series = models.PositiveIntegerField(null=True, blank=True)
    cover_image = models.ImageField(upload_to='books/', null=True, blank=True)
    description = models.TextField(blank=True)
    genre = models.ManyToManyField('Genre', blank=True)
    num_pages = models.PositiveIntegerField(null=True, blank=True)
    subgenre = models.ManyToManyField('Subgenre', blank=True)

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])


    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    bio = models.TextField(blank=True)
    photo = models.ImageField(upload_to='authors/', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Genre(models.Model):
    name = models.CharField(max_length=100,  unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='genre_name_case_insensitive_unique',
                violation_error_message = "Genre already exists"
            ),
        ]
    
class Series(models.Model):
    name = models.CharField(max_length=200)  
     # Number of books in the series
    total_books = models.PositiveIntegerField(default=0) 
    author = models.ForeignKey('Author', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'series'
    
class SubGenre(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'subgenres'

        constraints = [
        UniqueConstraint(
            Lower('name'),
            name='subgenre_name_case_insensitive_unique',
            violation_error_message = "Subgenre already exists"
        ),
    ]
    
class BookInstance(models.Model):

    def get_due_date():
        return date.today() + timedelta(days=30)

    @property
    def is_overdue(self):
        # check if due back is empty/populated - if populated, compares with todays date
        return bool(self.due_back and date.today() > self.due_back)

    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    borrowed_date = models.DateField(null=True, blank=True)  
    due_back = models.DateField(null=True, blank=True)  
    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('o', 'On loan'),
        ('a', 'Available'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='a',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} ({self.book.title})'
    
class Review(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review_text = models.TextField(blank=True)
    rating = models.PositiveSmallIntegerField(choices=[(i, i) for i in range(6)], null=True, blank=True)  
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    '''
    class Meta:
        unique_together = ('book', 'user')
    '''

booknook/library/forms.py
from django import forms 


class BookTitleFilterForm(forms.Form):
    searchQuery = forms.CharField(required=False, 
                                  widget=forms.TextInput(attrs={'placeholder': 'Search by book or author', 
                                                                'style': 'width: clamp(250px, 30vw, 400px)', 
                                                                'class': 'form-control mx-2'}))
    
class RateAndReviewForm(forms.Form):
    rating = forms.IntegerField(widget=forms.HiddenInput())
    review = forms.CharField(
        widget=forms.Textarea(attrs={
            'rows': 5,
            'placeholder': 'Write your review here...',
            'class': 'form-control'
        })
    )

booknook/library/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from .models import Book, Author, Genre, SubGenre, BookInstance, Review
from django.views import View
from django.utils import timezone
from .forms import BookTitleFilterForm, RateAndReviewForm
from django.db.models import Q, Value, CharField, Avg
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from datetime import timedelta
from django.db.models.functions import Concat


class BookListView(ListView):
    model = Book
    template_name = 'books.html'
    context_object_name='books'  

    def get(self, request, *args, **kwargs):
        if request.GET.get('searchQuery') == "" and request.GET.get('subgenre') == "":
            return redirect('books')  
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        books = Book.objects.all()
        search_query = self.request.GET.get('searchQuery')
        subgenre_query = self.request.GET.get('subgenre')

        if search_query:
            # First, search for books by title
            books_matching_title = books.filter(title__icontains=search_query)
            
            # if there is a book matching the search term title, return it
            if books_matching_title.exists():
                return books_matching_title
            
            # next, create a virtual column for all authors' full names
            authors = Author.objects.annotate(
                full_name=Concat('first_name', Value(' '), 'last_name', output_field=CharField()))
            
            # check to see if the author's name is in the queryset of author full names
            matching_authors = authors.filter(full_name__icontains=search_query)

            if matching_authors.exists():
                # if a matching name exists, filter books by that name
                books_matching_author_name = books.filter(author__in=matching_authors)
                return books_matching_author_name

            # if nothing matching is found, return 
            return books.none()  
        
        
        if subgenre_query:
            books = books.filter(subgenre__name__iexact=subgenre_query)

        # if no search query is provided, return all books
        return books

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subgenres'] = SubGenre.objects.all()

        context['form'] = BookTitleFilterForm()
        return context

class AuthorListView(ListView):
    model = Author
    template_name = 'authors.html'
    context_object_name='authors'

class GenreListView(ListView):
    model = Genre
    template_name = 'genres.html'
    context_object_name='genres'

def index_view(request):
    return render(request, 'index.html')

class BookDetailView(DetailView):
    model = Book

    def post(self, request, *args, **kwargs):
        form = RateAndReviewForm(request.POST)
        book = self.get_object()
        user = self.request.user
        if user.is_authenticated:
            if form.is_valid():
                Review.objects.create(
                    book=book,
                    user=user,
                    rating=form.cleaned_data['rating'],
                    review_text=form.cleaned_data['review']
                )

                return redirect('book-detail', pk=book.pk)
        else:
            return redirect('login')
        self.object = book
        context = self.get_context_data(**kwargs)
        context['rate_review_form'] = form  
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        is_available = BookInstance.objects.filter(book=self.object, status='a').exists()
        context['is_available'] = is_available
        context['book_genres'] = self.object.genre.all()
        context['book_subgenres'] = self.object.subgenre.all()
        context['rate_review_form'] = RateAndReviewForm()
        context['reviews'] = Review.objects.filter(book=self.object).order_by('-created_at')
        context['star_range'] = range(1, 6)
        context['average_rating'] = Review.objects.filter(book=self.object).aggregate(Avg('rating'))['rating__avg'] or 0
        user = self.request.user

        if user.is_authenticated:
            context['user_borrowed_book_count'] = BookInstance.objects.filter(borrower=user).count()
            context['in_user_borrowed_list'] = BookInstance.objects.filter(book=self.object, borrower=user, status='o').exists()

        other_books = Book.objects.filter(author=self.object.author).exclude(id=self.object.id)
        context['other_books_by_author'] = other_books if other_books.exists() else None

        if self.object.series:
            context['series_books'] = (
                Book.objects.filter(series=self.object.series)
                .exclude(id=self.object.id)
                .order_by('num_in_series')
            )
        else:
            context['series_books'] = Book.objects.none()

        return context

   

class AuthorDetailView(DetailView):
    model = Author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["authors_books"] =   self.object.book_set.order_by('publication_date')[:4]

        return context
 

class LoanedBooksByUserListView(LoginRequiredMixin,ListView):
    model = BookInstance
    template_name = 'library/bookinstance_list_borrowed_user.html'


    def post(self, request, pk):
        book = get_object_or_404(Book, id=pk)
        book_inst = get_object_or_404(BookInstance, borrower=request.user, status='o', book=book)  

        action = request.POST.get("action")
        if action == "return":
            return self.return_book(request, book_inst)
        elif action == "renew":
            return self.renew_book(request, book_inst)
        else:
            print("invalid action type submitted")
        
    
    def return_book(self, request, book_inst):
        book_inst.status = 'a'
        book_inst.borrower = None
        book_inst.borrowed_date = None
        book_inst.due_back = None
        book_inst.save()
        messages.success(request, f"Thank you for returning '{book_inst.book.title}'!")
        return redirect('borrowed-books')

    def renew_book(self, request, book_inst):
        borrow_day_limit = 90
        if ((book_inst.due_back -  book_inst.borrowed_date).days <= borrow_day_limit):
            book_inst.due_back = book_inst.due_back + timedelta(days=30)
            book_inst.save()
            messages.success(request, f"You've renewed '{book_inst.book.title}' by 30 days!")
        else:
            messages.error(request, f"You can't renew '{book_inst.book.title}' because you've already borrowed it for 90 days!")
        return redirect('borrowed-books')


    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact='o')
            .order_by('due_back')
        )


class BorrowBookView(LoginRequiredMixin, View):
    def post(self, request, pk):
        return self.process_borrow_request(request, pk)

    def process_borrow_request(self, request, pk):
        book = get_object_or_404(Book, id=pk)
        available_instance = BookInstance.objects.filter(book=book, status='a').first()

        user_borrowed_book_count = BookInstance.objects.filter(borrower=request.user).count()

        if available_instance and user_borrowed_book_count < 5:
            available_instance.borrower = request.user
            available_instance.status = 'o'  
            available_instance.borrowed_date = timezone.now().date()
            available_instance.due_back = timezone.now().date() + timedelta(days=30)
            available_instance.save()

        return redirect('book-detail', pk=pk)

booknook/library/templates/library/author_detail.html
{% extends 'base.html' %}
{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2">
            <div class="col book-detail-cover-img d-flex justify-content-center mb-3">
                {%if author.photo %}
                    <img src="{{author.photo.url}}" alt="{{author.first_name}} {{author.last_name}} photo" class="img-thumbnail resized-img">
                {%else%}
                    <img src="{{MEDIA_URL}}/authors/placeholder.png" class="card-img-top"  alt="placeholder img">
                {%endif%}
            </div>
            <div class="col py-4">
                <h1>{{author.first_name}} {{author.last_name}}</h1>
                    {% if author.bio %}
                    <p class="py-3 fs-5">
                        {{author.bio}}
                    </p>
                    {% endif %}
            </div>
        </div>
    </div>
    {% if authors_books %}
        <div class="container px-4 px-lg-5 mt-5">      
            <h5>Books by {{author.first_name}} {{author.last_name}}:</h5>
                <div class="d-flex books-by-author p-3 rounded row row-cols-1 row-cols-sm-2 row-cols-md-4 row-cols-lg-4">
                {% for book in authors_books %}
                    <div class="card author-book m-3" >
                        <img src="{{book.cover_image.url}}" class="card-img-top" alt="{{book.title}}">
                        <div class="card-body">
                            <h5 class="card-text"><a href="{{book.get_absolute_url}}" class="author-book-link">{{book.title}}</a></h5>
                        </div>
                    </div>
                {%endfor%}
                </div>
        </div>
    {% endif %}
</section>

{% endblock %}

booknook/library/templates/library/author_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container px-4 px-lg-5 mt-5 text-center">
    <h1 class="display-1">Authors</h1>
</div>
<section class="py-3">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 justify-content-center">
            {% for author in authors %}
            <div class="col mb-5">
                <div class="card author-card">
                    {%if author.photo %}
                        <img src="{{author.photo.url}}" class="card-img-top"  alt="{{author.first_name}} {{author.last_name}} photo">
                    {%else%}
                        <img src="{{MEDIA_URL}}/authors/placeholder.png" class="card-img-top"  alt="placeholder image">
                    {%endif%}
                    <div class="card-body text-center">
                        <h4>{{author.first_name}} {{author.last_name}}</h4>
                        <a href="{{ author.get_absolute_url }}" class="btn btn-secondary rounded border">About</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <li>No authors found.</li>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

booknook/library/templates/library/book_detail.html
{% extends 'base.html' %}
{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2">
            <div class="col book-detail-cover-img d-flex justify-content-center">
                {%if book.cover_image %}
                    <img src="{{book.cover_image.url}}" class="card-img-top mt-3 rounded-0 book-img" alt="{{book.title}} book cover">
                {%else%}
                    <img src="{{MEDIA_URL}}/authors/placeholder.png" class="card-img-top book-img"  alt="placeholder image">
                {%endif%}            
            </div>
            <div class="col py-4">
                {% if book.series %}
                <h4 class="fst-italic text-secondary">{{book.series}} #{{book.num_in_series}}</h4>
                {% endif %}
                <h1>{{book.title}}</h1>
                <h5><a href="{{ book.author.get_absolute_url }}" class="author-link">{{ book.author }}</a></h5>
                <div class="rating mb-2">
                    {% for i in star_range %}
                        {% if i <= average_rating %}
                            <span class="star-rating-average">&#9733;</span>  {# filled star #}
                        {% else %}
                            <span class="star-rating-average">&#9734;</span>  {# empty star #}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="genres-subgenres my-3">
                    {%if book_genres %}
                        {% for book_genre in book_genres %}
                            <button type="button" class="btn rounded-pill book-genre-button text-white">
                                {{book_genre}}</button>
                        {%endfor%}
                    {% endif %}
                    {%if book_subgenres %}
                        {% for book_subgenre in book_subgenres %}
                            <button type="button" class="btn rounded-pill book-subgenre-button text-white">
                                {{book_subgenre}}</button>
                        {%endfor%}
                    {%endif%}
                </div>
                <div class="book-detail-about mb-3">
                {% if book.description %}
                    <p class="py-3 fs-5">
                        {{book.description}}
                    </p>
                    {% endif %}
                    <h6 class="text-secondary">Published {{book.publication_date}}<h6>
                    {%if book.num_pages %}
                        <h6 class="text-secondary">Pages: {{book.num_pages}}</h6>
                    {%endif%}
                </div>
                <div>
                    {% if user.is_authenticated %}
                        {% if in_user_borrowed_list %}
                            <h6 class="text-success">You have borrowed this book! &#9989;</h6>
                        {% elif is_available and user_borrowed_book_count < 5 %}
                            <form action="{% url 'borrow-book' book.pk %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn borrow-btn-detail text-white my-2">Borrow this book</button>
                            </form>
                        {% elif not in_user_borrowed_list and user_borrowed_book_count >= 5 %}
                            <h6 class="text-danger">You've already reached the 5 book limit! Return a book to borrow this one.</h6>
                        {% else %}
                            <h6 class="text-warning">This book isn't in stock right now.</h6>
                        {% endif %}
                    {% else %}
                        <h6>You'll need to <a href="{% url 'login' %}">log in</a> to borrow a book!</h6>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="container px-4 px-lg-5 mt-5" id="rate-review">
        <h3>What did you think of {{book.title}}?</h3>
        <form method="post">
            {% csrf_token %}
            <div class="star-rating">
                <label for="star-1" class="star">&#9734;</label>
                <label for="star-2" class="star">&#9734;</label>
                <label for="star-3" class="star">&#9734;</label>
                <label for="star-4" class="star">&#9734;</label>
                <label for="star-5" class="star">&#9734;</label>
            </div>
            {{ rate_review_form.as_p }}
            <button type="submit" class="btn rate-review-button text-white my-2">Submit</button>
        </form>
    </div>
    <div class="container px-4 px-lg-5 mt-5">
        <h3>Ratings & Reviews</h3>
        {% if reviews %}
            {% for review in reviews %}
            <div class="review mb-4 p-3 border rounded">
                <div class="d-flex justify-content-between align-items-center">
                    <strong>{{ review.user.username }}</strong>
                    <small class="text-muted">{{ review.created_at|date:"F j, Y" }}</small>
                </div>
                <div class="rating mb-2">
                    {% for i in star_range %}
                        {% if i <= review.rating %}
                            <span>&#9733;</span> {# filled star #}
                        {% else %}
                            <span>&#9734;</span>  {# empty star #}
                        {% endif %}
                    {% endfor %}
                </div>
                <p>{{ review.review_text }}</p>
            </div>
            {% endfor %}
        {% else %}
            <p>No reviews yet. Be the first to leave one!</p>
        {% endif %}
    </div>

</section>

{% endblock %}

booknook/library/templates/library/book_list.html
{% extends 'base.html' %}
{% block content %}
<section>
    <div class="container px-4 px-lg-5 mt-5">
            <div class="d-flex justify-content-center my-3">
                <div class="search-container" id="search">
                    <form class="d-flex search-form p-3" method="GET" action="{% url 'books' %}">
                        {{ form.searchQuery }}
                        <button class="btn btn-dark" type="submit">Search</button>
                    </form>
                </div>
            </div>
            <div class="d-flex justify-content-center mb-5 mt-3 subgenre-container">
                {% for subgenre in subgenres %}
                    {% cycle '#2f888e' '#2384a2' '#467cae' '#746fab' '#996097' '#b05475' as bg_colours silent  %}
                    <a href="?subgenre={{ subgenre.name|urlencode }}#search"
                        class="btn text-white rounded m-1 {% if request.GET.subgenre == subgenre.name %}border border border-dark border-2{% endif %}"
                        style="background-color: {{ bg_colours }};">
                        {{ subgenre.name }}
                    </a>
                {% endfor %}
            </div>
        <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 justify-content-center">
            {% for book in books|dictsort:"publication_date" %}
            <div class="col mb-5">
                <div class="card h-100 rounded-0 book-card">
                    {%if book.cover_image %}
                        <img src="{{book.cover_image.url}}" class="card-img-top mt-3 rounded-0" alt="{{book.title}} book cover">
                    {%else%}
                        <img src="{{MEDIA_URL}}/authors/placeholder.png" class="card-img-top"  alt="placeholder image">
                    {%endif%}
                    <div class="card-body">
                        <div class="card-body-text">
                            <h4 class="card-title">{{book.title}}</h4>
                            <p class="card-text mb-2">{{book.author}}</p>
                        </div>
                        <a href="{{ book.get_absolute_url }}" class="btn borrow-btn-list text-white">Borrow</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>There are no books to display at the moment</p>
            {%endfor %}
        </div>
    </div>
</section>
{% endblock %}

booknook/library/templates/library/bookinstance_list_borrowed_user.html
{% extends "base.html" %}

{% block content %}

<div class="d-flex justify-content-center m-5">
    <div class="p-4 my-4 rounded login-form-container border border-secondary bg-light w-100">
        <h1 class="my-2">Borrowed books</h1>

        {% if bookinst.is_overdue %}
            <div class="alert alert-danger" role="alert">
                You have overdue books!
            </div>
        {% endif %}

        {% if messages %}
        <div class="messages">
            {% for message in messages %}
                {% if "success" in message.tags %}
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                {% else %}
                    <div class="alert alert-danger">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}

        {% if bookinstance_list %}

        <table class="table my-5">
            <thead>
                <tr>
                    <th>Book Title</th>
                    <th>Borrowed Date</th>
                    <th>Due Date</th>
                    <th>Return</th>
                    <th>Renew</th>
                </tr>
            </thead>
            <tbody>
                {% for bookinst in bookinstance_list %}
                <tr>
                    <td><a class="link-dark" href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a></td>
                    <td>{{bookinst.borrowed_date}}</td>
                    <td>{{ bookinst.due_back }}</td>
                    <td>
                        <form action="{% url 'book-action' bookinst.book.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="action" value="return">
                            <button type="submit" class="btn return-btn btn-sm text-white">Return</button>
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'book-action' bookinst.book.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="action" value="renew">
                            <button type="submit" class="btn btn-secondary btn-sm text-white">Renew</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
          </table>

        {% else %}
        <p class="mt-4">You don't have any borrowed books right now.</p>
        <a class="link-dark" href="{% url 'books'%}">Click here to view books to borrow!</a>
        {% endif %}

    </div>
</div>

{% endblock %}

booknook/library/templates/library/same_books_in_series.html
{%if series_books %}
<div class="container px-4 px-lg-5 mt-5">      
    <h5>Also in this series:</h5>
        <div class="d-flex books-by-author p-3 rounded row row-cols-1 row-cols-sm-2 row-cols-md-4 row-cols-lg-4">
        {% for book in series_books %}
            <div class="card author-book m-3" >
                {%if book.cover_image %}
                    <img src="{{book.cover_image.url}}" class="card-img-top rounded-0" alt="{{book.title}} book cover">
                {%else%}
                    <img src="{{MEDIA_URL}}/authors/placeholder.png" class="card-img-top"  alt="placeholder image">
                {%endif%}      
                <div class="card-body">
                    <h5 class="card-text"><a href="{{book.get_absolute_url}}" class="author-book-link">{{book.title}}</a></h5>
                </div>
            </div>
        {%endfor%}
        </div>
</div>
{% else %}
   {% if other_books_by_author %}
    <div class="container px-4 px-lg-5 mt-5">      
        <h5>Also by {{book.author}}:</h5>
            <div class="d-flex books-by-author p-3 rounded">
            {% for book in other_books_by_author %}
                <div class="card author-book mx-3" >
                    <img src="{{book.cover_image.url}}" class="card-img-top" alt="{{book.title}}">
                    <div class="card-body">
                        <p class="card-text"><a href="{{book.get_absolute_url}}" class="author-book-link">{{book.title}}</a></p>
                    </div>
                </div>
            {%endfor%}
            </div>
    </div>
    {% endif %}
{% endif %}